name: Run Performance tests blog.vizallati.guru

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: |
          sudo apt install nodejs -y 
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install ./google-chrome-stable_current_amd64.deb -y
          npm install

      - name: Run tests
        run: |
          ufw allow 9222
          npm test run




